### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by 5m1Ly** [VenomXNL/ObjectNameFromHash#2]
Use this cfx function instead of looping over a whopping 53859 tables within a table

GetEntityArchetypeName(Entity)

Should increes the speed of the script

**Comment by VenomXNL** [comment]
Back then (IF i'm correct) this function either wasn't known, exposed or possible yet. I totally agree that this (entire) script is not 'useful' anymore these days. Back in the days when I needed a "quick" solution I had asked multiple (read: dozens) of times on the forums for a solution to get the object name from it's has an never got a decent answer except links to other githubs which had smaller lists of object names.

These days it's even easier to just use CodeWalker to (instantly) get the object name you need for example. I personally aren't upgrading/updating this script anymore, but If you are absolutely certain that this will work (the call, because I don't have anytime to test/confirm it sorry), you might want to do a pull request which I will then confirm if you want :)
